### ISSUE TITLE
Publish `eslint-formatter-teamcity` as a mirror of this package

### ISSUE THREAD

**Issue by Hypnosphi** [andreogle/eslint-teamcity#15]
This will allow writing just `eslint --format teamcity`, see https://eslint.org/docs/developer-guide/working-with-custom-formatters#packaging-the-custom-formatter

**Comment by andreogle** [comment]
Great idea! I wasn't aware the ESLint could extract the name from the `eslint-formatter-` prefix

Do you know of a simple way to do this with mirroring? This isn't really something I'm familiar with

**Comment by Hypnosphi** [comment]
I never did this, but one idea is to create a branch with another name in `package.json` and keep it in sync with master

**Comment by andreogle** [comment]
So I spent some time looking into this and I'm not really convinced it's worth the effort of maintaining a separate branch or mirror, making sure they're keep in sync, published at the same time etc. so that we can have `--format teamcity` instead of `--format eslint-teamcity`

Looking back in hindsight, if I had known about the convention for naming formatters, I would definitely have gone with `eslint-formatter-teamcity`. If a simpler way becomes available for maintaining 2 packages from 1 repo or if there is something I missed, I'm totally open to it, but for now it's not something I'm going to follow through with.

Thanks for the suggestion nonetheless! 👍

**Comment by Hypnosphi** [comment]
> `--format eslint-teamcity`

This doesn't work for me:
```
Error: Cannot find module './formatters/eslint-teamcity'
```

Only this works:
```
--format ./node_modules/eslint-teamcity/index.js
```

**Comment by andreogle** [comment]
Ah sorry, that's what I meant - my mistake.

It's not ideal compared to just `--format eslint-teamcity` but I think it still outweighs the alternatives
