### ISSUE TITLE
Formatter has to be used with path 

### ISSUE THREAD

**Issue by Franziskus1988** [andreogle/eslint-teamcity#184]
Hey ho. 

According to the [EsLint docs for formatters](https://eslint.org/docs/developer-guide/working-with-custom-formatters) you can use formatters in a more generic way when use the following naming scheme: `eslint-formatter-$NAME$`.

What about renaming this package to `eslint-formatter-teamcity`, so that it can be used with `eslint -f teamcity`. 

E.g. for those using Yarn's pnp mode this would be beneficial. 

What do you think?

**Comment by andreogle** [comment]
Hey!

Yeah this was actually [raised a while ago](https://github.com/andreogle/eslint-teamcity/issues/15). I shut down the issue because I didn't want to maintain two separate repos. However, this package doesn't get many updates these days so I'm fine renaming it to conform to the ESLint guidelines and slowly deprecating this one.

I've published it as a [new package](https://www.npmjs.com/package/eslint-formatter-teamcity) (under a [new repo](https://github.com/andreogle/eslint-formatter-teamcity) too). I haven't had a chance to test it out properly yet - I just renamed some things and updated the README - but feel free to give it a try and let me know if you have any issues

**Comment by Franziskus1988** [comment]
Cool. Thanks. I will try it out and let you know.

**Comment by andreogle** [comment]
@Franziskus1988 any issues with the new package?

**Comment by andreogle** [comment]
Closing this. Feel free to re-open if there are any issues with the new package

**Comment by Franziskus1988** [comment]
Thank you! Everything is working fine. 

...Sorry for late answer, I was distracted by other stuff.... 😢
