### ISSUE TITLE
Reporting issues in the TeamCity UI

### ISSUE THREAD

**Issue by WattsC-90** [andreogle/eslint-teamcity#5]
Hi,
I have implemented this as a build step on teamcity, but the only place that warnings appear to be reported is in the build log. 
Do you know how to report the warnings up onto the UI? you show a screenshot with the errors but i cannot tell where that screen is on the UI? 
I am using Teamcity 9.1.7. 
Thanks for the really useful package, just trying to understand how to utilise the reporting feature.

A further issue i have, is that we do not use a package.json file, only a gulpfile.js to run this, which means we lose the configuration options. Can these be added as command line params? or is there another way to configure the package when it runs? I would like to enable the summary reporting.

**Comment by andreogle** [comment]
Hey!
1. The issues should be reported on the Overview tab for the build. I'm running TeamCity 10.0.2 but the UI is the same. How are you running ESLint in your build step?
   ![screen shot 2016-11-17 at 16 34 32](https://cloud.githubusercontent.com/assets/4114009/20393339/39923666-ace4-11e6-9780-138569df3710.png)
2. Unfortunately there is currently no way to pass in command line params to replace the `package.json` config settings. I'm not sure that this would be possible since this eslint-teamcity is just piggy-backing on the format option of ESLint. It could be, but would need to investigate it. Is there any reason you can't add a `package.json`?

http://eslint.org/docs/user-guide/command-line-interface#f---format

**Comment by WattsC-90** [comment]
Hi,
Thanks for the speedy response..:
1) The issues do (i.e. errors) but I would like the warnings to appear as well. The warnings get hidden under "tests passed", rather than shown on the overview page. The screenshot below (highly trimmed to prevent sensitive data publishing unfortunately), show that 13 tests passed, but if i look in the build log, there are lots of warnings.

![image](https://cloud.githubusercontent.com/assets/10712792/20394230/c28eff0c-acd6-11e6-8d36-0d4ad54c683e.png)
but in the build log:
![image](https://cloud.githubusercontent.com/assets/10712792/20394861/e9301b26-acd8-11e6-95d6-4f4ff1f13a7c.png)

I would expect the warnings to be shown on the UI, rather th

2) Visual Studio goes all belly up if package.json is included at project level, as opposed to solution level. If a partial package.json is dropped in, visual studio fails to load it as it is a partial package.json, missing vital components! :(

**Comment by andreogle** [comment]
1. Ah I see what you mean. I'm not sure about the warnings since I have them disabled for the projects I'm working on. I'll have to investigate this and get back to you.
2. I'm not sure I can help with this then unfortunately. I'll look into command line params but from what I've seen so far, it doesn't seem possible to pass arguments to the formatter or access arguments from the ESLint command.

**Comment by WattsC-90** [comment]
1) Thanks, it may be that theres an option on TC to enable visibility of warnings, but cant see it and dont know of one. I suspect its a format of the TC message that gets output from the ESLint module.

2) As a side note, related to this, why would the summary be disabled by default? is there a disadvantage to this being enabled?

**Comment by andreogle** [comment]
Yeah I think so too. TeamCity docs are not the most straight forward so still trying decipher what exactly the issue is. Haven't had much time to dig deep into this yet since I'm quite busy at the moment. Warnings are reported using using testStdOut so it's got something to do with that
https://confluence.jetbrains.com/display/TCD10/Build+Script+Interaction+with+TeamCity

I wasn't sure of the impact that it would have if people were reporting on other TeamCity stats ( especially since I didn't use the statistics feature myself). I just checked out the statistics page and I don't actually see a reason for it to be disabled at all. Users are free to create their own charts with specific statistics so I can't see how it would conflict with anything existing or have any disadvantages. I'll try rework it soon to always report on summary statistics.

**Comment by andreogle** [comment]
Ok so I've done quite a bit of digging into the warnings issue. It seems like there is no way to get the warnings to display on the overview tab - in the way that errors get reported. Right now, it's reporting warnings using `testStdOut` tab which logs to the build log (as you mentioned above). Without the `testStdOut` message, warnings **do not** get reported in the build log.

Without testStdOut:
![screen shot 2016-11-23 at 09 56 56](https://cloud.githubusercontent.com/assets/4114009/20554408/75daadcc-b164-11e6-8d69-b27e7940d517.png)

With testStdOut:
![screen shot 2016-11-23 at 09 57 14](https://cloud.githubusercontent.com/assets/4114009/20554418/8037b8f0-b164-11e6-807f-7c1e630de3a5.png)

The TeamCity docs are really not very clear with this at all, so I'm open to improvements if someone does find a way to report warnings/output on an easier to access page.

In the meantime, I've released v1.3.1 which will always output build statistic values. No need for package.json config! Let me know what you think.

**Comment by WattsC-90** [comment]
just been looking at this: 
[Jetbrains Youtrack: TW-42729](https://youtrack.jetbrains.com/issue/TW-42729)

seems like its an area for improvement, but could suggest an alternative until then. If its something you are interested in pursuing anyway

**Comment by andreogle** [comment]
I'm not sure exactly what you mean. Implement a function to log the warnings to a file (and then a new tab can be setup to view the warnings)? That could be something worth doing in the future - depending on the complexity.

**Comment by WattsC-90** [comment]
it might be possible? i do file logging for reports currently in TeamCity, just seems a bit over the top. Maybe this should be marked as a future enhancement for when TC guys sort that feature request out?

**Comment by andreogle** [comment]
Yeah I think it should be possible. It's definitely over the top but TeamCity doesn't really seem to care about this very much.

I'm going to close for now, but I'll mark as a future enhancement/investigation.
